ja:
  sex:
    male: '男性'
    female: '女性'
  married_status:
    unanswered_ms: '未回答'
    unmarried: '未婚'
    divorce: '離婚'
    widowed: '死別'
  sibling:
    0: '未回答'
    1: '長男・長女'
    2: '次男・次女'
    3: '三男・三女'
    4: 'その他'
  income:
    0: '未回答'
    1: '200万円未満'
    2: '200万円以上400万円未満'
    3: '400万円以上600万円未満'
    4: '600万円以上800万円未満'
    5: '800万円以上1000万円未満'
    6: '1000万円以上2000万円未満'
    7: '2000万円以上3000万円未満'
    8: '3000万円以上'
